[package]
name = "warheads-lib"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
